# Generated by Django 4.1.3 on 2023-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='diskr',
            field=models.TextField(default='default dis', verbose_name='Задача'),
            preserve_default=False,
        ),
    ]
